# This file specifies the exclusions needed for compatibility with older Go versions and dependencies.
# It is merged with the main .golangci.yml file to run the linter using the latest dependencies and go.mod.
linters:
  exclusions:
    rules:
      # patch for latest deps
      - text: 'for loop can be changed to use an integer range \(Go 1.22\+\)' # remove after go 1.22+
        linters:
          - intrange
      - text: 'rangeint: for loop can be modernized using range over int' # remove after go 1.22+
        linters:
          - modernize
      - text: 'waitgroup: Goroutine creation can be simplified using WaitGroup.Go' # remove after go 1.25+
        linters:
          - modernize
