name: CI (optional)
on:
  workflow_dispatch:
    inputs:
      debug_ssh:
        description: "Enable SSH debug with tmate, see https://github.com/marketplace/actions/debugging-with-tmate"
        required: false
        type: boolean
        default: false
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1" # Each Monday

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-latest-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: use latest go.mod
        run: cp .github/latest-deps/go.mod go.mod && cp .github/latest-deps/go.sum go.sum
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.1" # update together with dev.dockerfile
      - uses: golangci/golangci-lint-action@v6
        with:
          verify: true
          version: "v1.64.7" # update together with dev.dockerfile
